version: '3'
services:
  resource-gen:
    container_name: resource-gen
    image: resource-gen-img
    build:
      context: ./resource-gen
    volumes:
      - ./output:/usr/src/output
  stream-backpressure:
    container_name: stream-backpressure
    mem_limit: 256m
    build:
      context: .
      dockerfile: Dockerfile.streamBackpressure
    volumes:
      - ./output:/usr/src/output
  stream-backpressure-2:
    container_name: stream-backpressure-2
    mem_limit: 256m
    build:
      context: .
      dockerfile: Dockerfile.streamBackpressure2
    volumes:
      - ./output:/usr/src/output
  stream-backpressure-2-fixed:
    container_name: stream-backpressure-2-fixed
    mem_limit: 256m
    build:
      context: .
      dockerfile: Dockerfile.streamBackpressure2Fixed
    volumes:
      - ./output:/usr/src/output
  basic-stream:
    mem_limit: 512m
    build:
      context: .
      dockerfile: Dockerfile.basicStream
    volumes:
      - ./output:/usr/src/output
  concurrent-stream:
    mem_limit: 512m
    build:
      context: .
      dockerfile: Dockerfile.concurrentStream
    volumes:
      - ./output:/usr/src/output

volumes:
  data:
